"""add dsa wht/net commission amount to commission_lines

Revision ID: 752567f509cf
Revises: 8b536e188727
Create Date: 2026-09-08 16:51:43.202301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752567f509cf'
down_revision: Union[str, None] = '8b536e188727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_lines', sa.Column('wht_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('commission_lines', sa.Column('net_commission_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_lines', 'net_commission_amount')
    op.drop_column('commission_lines', 'wht_amount')
    # ### end Alembic commands ###
