"""add dtl.branch_id

Revision ID: 7849917df8fc
Revises: 90cdb0176307
Create Date: 2026-09-03 16:33:19.578578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7849917df8fc'
down_revision: Union[str, None] = '90cdb0176307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtls', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dtls', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dtls', type_='foreignkey')
    op.drop_column('dtls', 'branch_id')
    # ### end Alembic commands ###
