"""add dtl.dtl_account_no

Revision ID: 85aac009fc1c
Revises: 7700fc95def1
Create Date: 2026-09-04 11:00:11.806500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85aac009fc1c'
down_revision: Union[str, None] = '7700fc95def1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtls', sa.Column('dtl_account_no', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dtls', 'dtl_account_no')
    # ### end Alembic commands ###
