"""initial schema

Revision ID: 90cdb0176307
Revises: 
Create Date: 2026-09-03 14:19:57.903133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cdb0176307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dtls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtl_code', sa.String(length=100), nullable=False),
    sa.Column('dtl_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtls_dtl_code'), 'dtls', ['dtl_code'], unique=True)
    op.create_table('dsas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsa_code', sa.String(length=100), nullable=False),
    sa.Column('dsa_name', sa.String(length=255), nullable=False),
    sa.Column('dsa_account_no', sa.String(length=100), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsas_dsa_code'), 'dsas', ['dsa_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('BRANCH_MANAGER', 'BUSINESS_MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Enum('BRANCH', 'ORG_WIDE', name='run_type'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'LOCKED', 'PAID', name='run_status'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_runs_period'), 'commission_runs', ['period'], unique=False)
    op.create_table('dsa_dtl_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsa_id', sa.Integer(), nullable=False),
    sa.Column('dtl_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dsa_id'], ['dsas.id'], ),
    sa.ForeignKeyConstraint(['dtl_id'], ['dtls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsa_id', 'effective_from', name='uq_dsa_assignment_start')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_type', sa.Enum('BRANCH_MANAGER', 'BUSINESS_MANAGER', name='upload_type'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_check_no', sa.String(length=100), nullable=False),
    sa.Column('client_account_no', sa.String(length=100), nullable=False),
    sa.Column('application_number_ess', sa.String(length=255), nullable=True),
    sa.Column('reported_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('branch_name_raw', sa.String(length=255), nullable=True),
    sa.Column('dsa_code', sa.String(length=100), nullable=False),
    sa.Column('dsa_account_no', sa.String(length=100), nullable=True),
    sa.Column('dsa_name', sa.String(length=255), nullable=False),
    sa.Column('dtl_name', sa.String(length=255), nullable=True),
    sa.Column('dtl_code', sa.String(length=100), nullable=True),
    sa.Column('date_out_of_period_warning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_sales_client_account_no'), 'branch_sales', ['client_account_no'], unique=False)
    op.create_index(op.f('ix_branch_sales_dsa_code'), 'branch_sales', ['dsa_code'], unique=False)
    op.create_table('business_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('branch_name_raw', sa.String(length=255), nullable=True),
    sa.Column('employee_no', sa.String(length=100), nullable=True),
    sa.Column('customer_no', sa.String(length=100), nullable=True),
    sa.Column('account_no', sa.String(length=100), nullable=True),
    sa.Column('loan_type', sa.Enum('NL', 'RF', name='loan_type'), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('disbursement_amt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payout_to_client', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('letshego_topup', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('appl_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('client_disb_ext_account_no', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_transactions_client_disb_ext_account_no'), 'business_transactions', ['client_disb_ext_account_no'], unique=False)
    op.create_index(op.f('ix_business_transactions_employee_no'), 'business_transactions', ['employee_no'], unique=False)
    op.create_table('upload_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_row_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matched_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_sale_id', sa.Integer(), nullable=True),
    sa.Column('business_transaction_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'MATCHED_WITH_WARNING', 'UNMATCHED_IN_BUSINESS_FILE', 'UNMATCHED_IN_BRANCH_FILE', 'DUPLICATE', name='match_status'), nullable=False),
    sa.Column('match_notes', sa.Text(), nullable=True),
    sa.Column('commission_period', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_sale_id'], ['branch_sales.id'], ),
    sa.ForeignKeyConstraint(['business_transaction_id'], ['business_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matched_transactions_commission_period'), 'matched_transactions', ['commission_period'], unique=False)
    op.create_table('commission_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_run_id', sa.Integer(), nullable=False),
    sa.Column('matched_transaction_id', sa.Integer(), nullable=False),
    sa.Column('payee_type', sa.Enum('DSA', 'DTL', name='payee_type'), nullable=False),
    sa.Column('dsa_id', sa.Integer(), nullable=True),
    sa.Column('dtl_id', sa.Integer(), nullable=True),
    sa.Column('loan_type', sa.Enum('NL', 'RF', name='commission_line_loan_type'), nullable=False),
    sa.Column('base_used', sa.Enum('GROSS', 'NET', name='commission_base'), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_run_id'], ['commission_runs.id'], ),
    sa.ForeignKeyConstraint(['dsa_id'], ['dsas.id'], ),
    sa.ForeignKeyConstraint(['dtl_id'], ['dtls.id'], ),
    sa.ForeignKeyConstraint(['matched_transaction_id'], ['matched_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_run_id', sa.Integer(), nullable=False),
    sa.Column('original_commission_line_id', sa.Integer(), nullable=True),
    sa.Column('payee_type', sa.Enum('DSA', 'DTL', name='adjustment_payee_type'), nullable=False),
    sa.Column('dsa_id', sa.Integer(), nullable=True),
    sa.Column('dtl_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_run_id'], ['commission_runs.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dsa_id'], ['dsas.id'], ),
    sa.ForeignKeyConstraint(['dtl_id'], ['dtls.id'], ),
    sa.ForeignKeyConstraint(['original_commission_line_id'], ['commission_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_adjustments')
    op.drop_table('commission_lines')
    op.drop_index(op.f('ix_matched_transactions_commission_period'), table_name='matched_transactions')
    op.drop_table('matched_transactions')
    op.drop_table('upload_errors')
    op.drop_index(op.f('ix_business_transactions_employee_no'), table_name='business_transactions')
    op.drop_index(op.f('ix_business_transactions_client_disb_ext_account_no'), table_name='business_transactions')
    op.drop_table('business_transactions')
    op.drop_index(op.f('ix_branch_sales_dsa_code'), table_name='branch_sales')
    op.drop_index(op.f('ix_branch_sales_client_account_no'), table_name='branch_sales')
    op.drop_table('branch_sales')
    op.drop_table('uploads')
    op.drop_table('dsa_dtl_assignments')
    op.drop_index(op.f('ix_commission_runs_period'), table_name='commission_runs')
    op.drop_table('commission_runs')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dsas_dsa_code'), table_name='dsas')
    op.drop_table('dsas')
    op.drop_index(op.f('ix_dtls_dtl_code'), table_name='dtls')
    op.drop_table('dtls')
    op.drop_table('branches')
    # ### end Alembic commands ###
